import Link from "next/link";
import Image from "next/image";
import MealSearchInput from "./components/MealSearchInput";
import { Roboto } from "next/font/google";

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
})


export const metadata = {
    title: "All Meals",
    description: "Generated by create next app",
};

const MealsPage = async ({ searchParams }) => {
    const query = await searchParams?.search || "";

    const res = await fetch(
        `https://www.themealdb.com/api/json/v1/1/search.php?s=${query}`
    );
    const data = await res.json();
    const meals = data?.meals || [];

    return (
        <div className="p-4">
            <div className="flex justify-center mb-8">
                <MealSearchInput />
            </div>

            {meals.length > 0 ? (
                <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
                    {meals.map((meal) => (
                        <li
                            key={meal.idMeal}
                            className="border border-gray-200 p-4 rounded-xl shadow hover:shadow-lg transition"
                        >
                            <Link href={`/meals/${meal.idMeal}`} className={`block ${roboto.className}`}>
                                <Image
                                    src={meal.strMealThumb}
                                    alt={meal.strMeal}
                                    width={400}
                                    height={300}
                                    className="w-full h-48 object-cover rounded mb-4"
                                />
                                <h3 className="text-lg font-semibold text-blue-700">
                                    {meal.strMeal}
                                </h3>
                                <p className="text-sm text-gray-600">
                                    {meal.strArea} - {meal.strCategory}
                                </p>
                            </Link>
                        </li>
                    ))}
                </ul>
            ) : (
                <p className="text-center text-red-500 font-medium text-lg mt-10">
                    No meals found for "{query}"
                </p>
            )}
        </div>
    );
};

export default MealsPage;
