import React from "react";
export const metadata = {
    title: "Services",
    description: "Generated by create next app",
};

const Services = () => {
    return (
        <div className="min-h-screen text-gray-100 py-16 px-4 sm:px-10">
            <div className="max-w-4xl mx-auto text-center">
                <h1 className="text-4xl font-bold text-blue-600 mb-6">Our Services</h1>
                <p className="text-lg text-gray-600 mb-12">
                    At TalkSphere, we build powerful forum platforms that connect communities and encourage meaningful discussions.
                </p>

                <div className="grid md:grid-cols-3 gap-8">
                    <div className="p-6 bg-gray-700 rounded-2xl shadow-md hover:shadow-xl transition">
                        <h2 className="text-xl font-semibold mb-3 text-blue-700">Custom Forum Development</h2>
                        <p className="text-sm text-gray-300">
                            We use Next.js and React to build blazing-fast, SEO-friendly forums tailored to your audience and brand.
                        </p>
                    </div>

                    <div className="p-6 bg-gray-700 rounded-2xl shadow-md hover:shadow-xl transition">
                        <h2 className="text-xl font-semibold mb-3 text-blue-700">Authentication & Security</h2>
                        <p className="text-sm text-gray-300">
                            Integrated Firebase Auth and JWT to keep your users safe with smooth login/signup and secure session handling.
                        </p>
                    </div>

                    <div className="p-6 bg-gray-700 rounded-2xl shadow-md hover:shadow-xl transition">
                        <h2 className="text-xl font-semibold mb-3 text-blue-700">Admin & User Dashboards</h2>
                        <p className="text-sm text-gray-300">
                            Role-based dashboards to manage users, threads, and reports. Built with TailwindCSS for that clean UI drip.
                        </p>
                    </div>
                </div>

                <div className="mt-16">
                    <h3 className="text-2xl font-bold mb-4">Why Choose TalkSphere?</h3>
                    <ul className="text-left max-w-2xl mx-auto space-y-3">
                        <li className="text-gray-300">⚡ Fast performance with SSR & static generation using Next.js</li>
                        <li className="text-gray-300">🎯 Modern UI using TailwindCSS & React Hooks</li>
                        <li className="text-gray-300">🔐 Scalable, secure backend logic powered by Firebase + JWT</li>
                        <li className="text-gray-300">📊 Admin insights and moderation tools baked in</li>
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default Services;